version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app
networks:
  default:
    external:
      name: datanet
